apiVersion: v1
kind: ConfigMap 
metadata:
  name: webapp-config-map
data:
    ENVIRONMENT: Mostafa Hassan
    HOST: {{.Release.Name }}-websvc
    PORT:  {{ .Values.webservice.port| quote}}
    REDIS_HOST: {{.Release.Name}}-dbsvc
    REDIS_PORT: {{.Values.dbservice.port |quote}}
    REDIS_DB: "0"
