replicaCount: 3

webimage:
  repository: mostafahassan/webapp-python
  tag: ""

labels: 
    app: frontend-app

dbimage:
  repository: mostafahassan/redis
  tag: ""

dblables: 
  app: backend-db


webservice:
  type: NodePort
  port: 9000
  targetPort: 9000

dbservice:
  type: ClusterIP
  port: 6379

